language: java
jdk: oraclejdk8
dist: trusty
services:
  - docker

cache:
  directories:
    - "$HOME/.m2"

script:
  - mvn clean install
  - docker build -t kristiyang/hackconf:beer-service-$TRAVIS_BUILD_NUMBER ./server
  - docker push kristiyang/hackconf:beer-service-$TRAVIS_BUILD_NUMBER
  - echo "Done"
