POST {{host}}/beers
Content-Type: application/json

{
  "title": "Triple Karmeliet",
  "rank": 5,
  "imageLink": "https://s3.amazonaws.com/beertourprod/beers/share_pictures/000/000/036/original/tripel_karmeliet.png?1510165814"
}

###
GET {{host}}/beers

###
GET {{host}}/beers/1

###

POST {{host}}/reviews/1
Content-Type: application/json

{
  "rank": 2,
  "comment": "WOW"
}

###
